### ISSUE TITLE
Are you planning other positioning sensor in the future?

### ISSUE THREAD

**Issue by iu3qez** [ok1hra/IP-rotator#2]
Hi,

Happy user of the IP Interface. Really a great product.
Unfortunately my rotor had decided to give up: as usual the 500 ohm potentiometer is gone (I already tried to repair it.. But after a couple of weeks it broke again). 

As this is a weak point of this kind of rotor (Hy Gain, CDE etc), I'm thinking to replace the 500 ohm potentiometer with some other positioning system...  Also their cost has gone crazy lately.

What I have in my mind are:
1) a simple magnetic encoder;
2) a magnetometer
3) some other kind of potentiometer based position.

I know that the hardware and software well support the 3), what about the other 2? Would be possible to implement without drastic change in the code?

73 de Simone IU3QEZ

**Comment by ok1hra** [comment]
There are two options

1. use the analog input, i.e. if the sensor produces a voltage of 0-9V, you can connect it directly to the IP rotator
2. create an independent sensor that is connected to WiFi or Ethernet and sends location data via IP - it would require intervention in the code.

73, Dan OK1HRA
