### ISSUE TITLE
PWM issue ?

### ISSUE THREAD

**Issue by jrueschenschmidt** [ok1hra/IP-rotator#3]
Hello Dan,

I think I found a bug in line 1889. I assume it should be -3.

1886   case -2: {
1887   	if(PWMenable==true){
1888    	    if(abs(AzimuthTarget-Azimuth)<10){
1889        	**Status=3**;
1890            }
1891        }else{
1892    	    if(abs(AzimuthTarget-Azimuth)<2){
1893		Status=-3;
1894	    }
1895       }

73 de Joerg (DL3QQ)

**Comment by ok1hra** [comment]
Yes Joerg, it is bug.
Now fix in last release 20241009
TNX!

**Comment by ok1hra** [comment]
close
